from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from agents.coordinator_agent import coordinator_agent
import logging

router = APIRouter()

class ChatMessage(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    medicine_name: str | None = None
    history: list[ChatMessage] = []

@router.post("/chat")
async def chat_endpoint(req: ChatRequest):
    try:
        current_query = req.history[-1].content if req.history else ""
        
        # Initialize state with user message and medicine context
        initial_state = {
            "mode": "chat",
            "query": current_query,
            "history": [{"role": m.role, "content": m.content} for m in req.history],
            "medicine_name": req.medicine_name,
            "retrieved_chunks": [],
            "draft_answer": "",
            "fact_check_results": {},
            "citations": [],
            "summary": ""
        }
        
        # Run the agent pipeline
        final_state = await coordinator_agent(initial_state)
        
        # Return the answer (either summary or draft answer)
        # For chat, we might prefer the direct answer if it exists, 
        # but the current system puts the "answer" in 'draft_answer' or 'summary'.
        # Let's use draft_answer as the primary chat response for now, 
        # or summary if it's the only thing available.
        
        # Actually, for the chatbot, we probably want the 'draft_answer' 
        # (generated by generator_agent) which answers the SPECIFIC question.
        # 'summary' is usually for the general medicine summary.
        
        response_text = final_state.get("draft_answer") or final_state.get("summary") or "I'm sorry, I couldn't generate a response."
        
        return {"response": response_text}

    except Exception as e:
        logging.error(f"Error in chat endpoint: {e}")
        raise HTTPException(status_code=500, detail=str(e))